name: 📖 Deploy MkDocs to GitHub Pages

on:

  # Run when changes are made to the contents of the docs folder, the MkDocs config, or this workflow.
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/Deploy MkDocs.yml'
      - 'mkdocs.yml'

  # Allow manual triggering of the workflow.
  workflow_dispatch:

jobs:

  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: ✅ Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: 🐍 Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: '3.x'  # specify the Python version

      - name: ➕ Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r docs/requirements.txt

      - name: 👷‍♂️ Build & Deploy MkDocs
        run: |
          mkdocs build --strict --site-dir site
          test -f site/index.html
          test -f site/sitemap.xml
          mkdocs gh-deploy --force
